/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package projekcrud;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reyhan Agus P
 */
public class Booking extends javax.swing.JInternalFrame {

    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
        tampil_tabel_booking();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinFieldBeanInfo1 = new com.toedter.components.JSpinFieldBeanInfo();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        tno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_barang_booking = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        tdeskripsi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tharga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tpaket = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btntambah = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tjumlah = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jdate = new com.toedter.calendar.JDateChooser();
        twaktu = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("CIBIRU STORE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("BOOKING TEMPAT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jLabel3.setText("Nama Lengkap");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        jLabel4.setText("No. Handphone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        jLabel5.setText("Waktu");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, -1));
        getContentPane().add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 264, 30));

        tno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnoActionPerformed(evt);
            }
        });
        getContentPane().add(tno, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 264, 30));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        tabel_barang_booking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Paket", "Deskripsi", "Harga"
            }
        ));
        tabel_barang_booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_barang_bookingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_barang_booking);
        if (tabel_barang_booking.getColumnModel().getColumnCount() > 0) {
            tabel_barang_booking.getColumnModel().getColumn(1).setMinWidth(300);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 550, 160));

        jLabel6.setText("Paket yang dipilih");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        tdeskripsi.setEnabled(false);
        getContentPane().add(tdeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 256, 91));

        jLabel7.setText("Nama Paket");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel10.setText("Harga");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        tharga.setEnabled(false);
        getContentPane().add(tharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 256, 35));

        jLabel11.setText("Deskripsi");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        tpaket.setEnabled(false);
        getContentPane().add(tpaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 256, 35));

        jLabel12.setText("Silahkan Pilih Paket");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        btntambah.setText("Tambah");
        btntambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntambahMouseClicked(evt);
            }
        });
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        getContentPane().add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, -1, -1));

        jLabel9.setText("Jumlah Pesanan");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, -1, -1));
        getContentPane().add(tjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 70, 30));

        jLabel13.setText("Tanggal");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, -1, -1));
        getContentPane().add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));
        getContentPane().add(twaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnoActionPerformed

    private void tabel_barang_bookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_barang_bookingMouseClicked
        // TODO add your handling code here:
         int baris = tabel_barang_booking.rowAtPoint(evt.getPoint());
         String namaPaket, desk, hrg;
         
         namaPaket = tabel_barang_booking.getValueAt(baris, 0).toString();
         tpaket.setText(namaPaket);
         desk = tabel_barang_booking.getValueAt(baris, 1).toString();
         tdeskripsi.setText(desk);
         hrg = tabel_barang_booking.getValueAt(baris, 2).toString();
         tharga.setText(hrg);
    }//GEN-LAST:event_tabel_barang_bookingMouseClicked

    private void btntambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntambahMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btntambahMouseClicked

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        String nama_paket = tpaket.getText();
        String deskripsi = tdeskripsi.getText();
        int harga = Integer.parseInt(tharga.getText());
        String nama_lengkap = tnama.getText();
        int no_hp = Integer.parseInt(tno.getText());
    
        Date tanggal = (Date) jdate.getDate();
        SimpleDateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalDate = oDateFormat.format(tanggal);
        
        String time = twaktu.getText();
        
        int jumlah_pesanan = Integer.parseInt(tjumlah.getText());
        
        try {
            String query = "INSERT INTO booking (nama_lengkap,no_hp,tanggal,waktu,nama_paket,jumlah_pesanan) VALUES ('"+nama_lengkap+"','"+no_hp+"','"+tanggalDate+"','"+time+"','"+nama_paket+"','"+jumlah_pesanan+"')";
            
            Connection conn = testkoneksi.configDB();
            
            PreparedStatement s = conn.prepareStatement(query);
            
            s.execute();
            
            JOptionPane.showMessageDialog(null, "Data Barang Berhasil Ditambahkan");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Barang Gagal Ditambahkan");
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_tabel_booking();
    }//GEN-LAST:event_btntambahActionPerformed

    private void tampil_tabel_booking(){
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Nama Paket");
        tb.addColumn("Deskripsi");
        tb.addColumn("Harga");
        
        try {
            String query = ("SELECT nama_paket,deskripsi,harga FROM data_barang");
            
            Connection conn = testkoneksi.configDB();
            
            Statement s = conn.createStatement();
            
            ResultSet result = s.executeQuery(query);
            
            while(result.next()){
                tb.addRow(new Object[]{
                    result.getString(1),result.getString(2),result.getString(3)
                });
            }
            tabel_barang_booking.setModel(tb);
            
        } catch (Exception e) {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.components.JSpinFieldBeanInfo jSpinFieldBeanInfo1;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JTable tabel_barang_booking;
    private javax.swing.JTextField tdeskripsi;
    private javax.swing.JTextField tharga;
    private javax.swing.JTextField tjumlah;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tno;
    private javax.swing.JTextField tpaket;
    private javax.swing.JTextField twaktu;
    // End of variables declaration//GEN-END:variables
}
